service: serverless-app

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:us-west-1:641240258309:table/todos"

functions:
  getTodo:
    handler: handlers/get.run
    events:
      - http:
          path: todos/{id}
          method: get
      - cloudwatchLog:
          logGroup: "/aws/lambda/getTodo"
  createTodo:
    handler: handlers/create.run
    events:
      - http:
          path: todos
          method: post
      - cloudwatchLog:
          logGroup: "/aws/lambda/createTodo"

resources:
  Resources:
    TodosTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: todos
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
